### ISSUE TITLE
react native - android hatası

### ISSUE THREAD

**Issue by aytekinsahin** [abdurrahmanekr/bana-istedigini-sor#77]
hocam merhaba ,
React native ile projenin  önemli kısmını tamamladım aslında . 
IOS simulatörde sorunsuz çalışıyor . 
Android tarafında run ettiğimde uygulama açılmıyor. 
react native android keeps stopping diyor ve uygulama kapanıyor. 

Android studio da build hatasız alıyor . ancak run logları incelediğimde aşağıdaki hatayı görüntüledim .  3 gündür araştırıyorum bir çözüme varamadım .yaerdımcı olma şansınız var mıdır ? 

E/SoLoader: couldn't find DSO to load: libreactnativejni.so caused by: dlopen failed: library "libc++_shared.so" not found
E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.galvametalapp, PID: 6472
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so caused by: dlopen failed: library "libc++_shared.so" not found
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:31)
        at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)
        at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:25)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:944)
        at java.lang.Thread.run(Thread.java:764)

**Comment by abdurrahmanekr** [comment]
Merhaba, dostuma sorayım bakalım :/

@selmansamet hocam sen daha önce yaşadın mı böyle bir sorun?

**Comment by sametcodes** [comment]
Selamlar @aytekinsahin @abdurrahmanekr,

Daha önce böyle bir hatayla karşılaşmadım. Ama çıktıdaki **libc++_shared.so** kütüphane dosyası üzerinden gidebiliriz. İlgili kütüphane dosyasına baktığımda [şuraya](https://developer.android.com/ndk/guides/cpp-support) ve şu bilgiye ulaştım.

> LLVM's libc++ is the C++ standard library that has been used by the Android OS since Lollipop, and as of NDK r18 is the only STL available in the NDK.

Android versiyonun nedir? Lollipop versiyonundan eskiyse Studio'dan yeni bir versiyon kurarak deneyebilir misin?

*Not: uzun zamandır rn yazmıyorum :sweat_smile:*

**Comment by aytekinsahin** [comment]
selamlar @selmansamet @abdurrahmanekr 
7 ve sonrası tüm versiyonları denedim tek tek , 
o yüzden geç dönüyorum size ,
aşağıdaki kütüphaneleri projeme dahil ettim bunlardan kaynaklanmış olabilir mi sizce ? 
=>react-native-elements
=>react-native-router-flux
=>react-native-swiper
=>react-native-pdf

**Comment by aytekinsahin** [comment]
Selamlar tekrar . 
sorun pdf ten kaynaklanıyormuş . 
Çözemedim ancak projeden  kaldırdım şuan en azından çalışıyor . 
Yeni problemim  farklı olmakla beraber react native console da aşağıdaki gibi hata alıyorum .
Bir fikriniz var ise , paylaşırsanız sevinirim . 

Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:87)
    at XMLHttpRequest.dispatchEvent (event-target.js:172)
    at XMLHttpRequest.setReadyState (XMLHttpRequest.js:580)
    at XMLHttpRequest.__didCompleteResponse (XMLHttpRequest.js:394)
    at XMLHttpRequest.js:507
    at RCTDeviceEventEmitter.emit (EventEmitter.js:189)
    at MessageQueue.__callFunction (MessageQueue.js:366)
    at MessageQueue.js:106
    at MessageQueue.__guard (MessageQueue.js:314)
